In [470]:
from tabula import read_pdf
import pandas as pd
import numpy as np
pd.set_option('display.max_colwidth',None)

In [488]:
dfs = read_pdf('./resultados_ord2023_1_gral_bd.pdf',pages='all',area=[97,15,560,822])
len(dfs)

34

In [489]:
dfs[33].head()

,#,Carné,Apellidos y Nombres,Bu,Ma,Puntaje,Bu.1,Ma.1,Puntaje.1,Examen,Especialidad,Ingreso
0,922,39230051,SATURIO LOYOLA JELITSA LISVET,0,0,0.0,0,0,0.0,0.0,DERECHO Y CIENCIA POLITICAS,Ausente
1,923,24230145,SORIANO CORONEL IBETH PRISCILA,0,0,0.0,0,0,0.0,0.0,MEDICINA HUMANA,Ausente
2,924,39230122,TAYA VARGAS WENDY,0,0,0.0,0,0,0.0,0.0,DERECHO Y CIENCIA POLITICAS,Ausente
3,925,24230105,TIRADO VILLANUEVA LADY VALERIE,0,0,0.0,0,0,0.0,0.0,MEDICINA HUMANA,Ausente
4,926,24230060,VALDERRAMA RODRIGUEZ JENS CHRISTIAN,0,0,0.0,0,0,0.0,0.0,MEDICINA HUMANA,Ausente

In [493]:
df = pd.concat(dfs,ignore_index=True)
df.head(-1)

,#,Carné,Apellidos y Nombres,Bu,Ma,Puntaje,Bu.1,Ma.1,Puntaje.1,Examen,Especialidad,Ingreso
0,1.0,24230041.0,MONZÓN RODRÍGUEZ PAOLO FABIANO,25.0,8.0,93.598,30.0,18.0,133.992,227.590,MEDICINA HUMANA,SI
1,2.0,24230493.0,AMOROZ SANCHEZ MIGUEL ANGEL,26.0,8.0,97.668,30.0,25.0,126.845,224.513,MEDICINA HUMANA,SI
2,3.0,24230193.0,CUYATE CALDERON DIEGO STALIN,27.0,6.0,103.776,27.0,21.0,115.692,219.468,MEDICINA HUMANA,SI
3,4.0,24230353.0,ZAVALETA AGUIRRE BRYAN JHOSUE,21.0,3.0,82.413,28.0,8.0,134.044,216.457,MEDICINA HUMANA,SI
4,5.0,24230158.0,CRUZ ESPEJO ANDERSON ALEXANDER,22.0,7.0,82.407,30.0,18.0,133.992,216.399,MEDICINA HUMANA,SI
...,...,...,...,...,...,...,...,...,...,...,...,...
1018,938.0,21230011.0,CRUZ SÁNCHEZ GABRIELA BRYGUITTE,5.0,28.0,-8.182,7.0,31.0,3.902,-4.280,ENFERMERIA,NO
1019,939.0,24230381.0,ROSSELL GILIO FIORELLA STEFANY,8.0,29.0,3.009,7.0,43.0,-8.350,-5.341,MEDICINA HUMANA,NO
1020,940.0,31230071.0,ZAPATA PEREZ YOMARA SOLEDAD,2.0,19.0,-11.221,4.0,18.0,1.938,-9.283,EDUC. INICIAL,NO
1021,941.0,24230133.0,PELAEZ CORDOVA AKEMI MARIA,7.0,19.0,9.129,4.0,39.0,-19.503,-10.374,MEDICINA HUMANA,NO
1022,942.0,32230014.0,QUINTANA SILVA SHEYLA VANESSA,6.0,34.0,-10.226,9.0,51.0,-6.360,-16.586,EDUC. PRIMARIA,NO

In [494]:
all_index_test = np.array(list(range(1,944)))
review = np.array(df['#'].unique())
difference = np.setdiff1d(all_index_test,review)
difference

array([], dtype=int32)

In [495]:
df.shape

(1024, 12)

In [496]:
df['#'].isna().value_counts()

False    943
True      81
Name: #, dtype: int64

In [497]:
df[df['#'].isna()]

,#,Carné,Apellidos y Nombres,Bu,Ma,Puntaje,Bu.1,Ma.1,Puntaje.1,Examen,Especialidad,Ingreso
111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POLITICAS,NaN
112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2° COMUNICACION SOCIAL,NaN
114,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POLITICAS,NaN
115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2° LENGUA Y LITERATURA,NaN
117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POLITICAS,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
678,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CIENCIAS SOCIALES,NaN
694,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2° EDUC. PRIMARIA,NaN
698,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POLITICAS,NaN
699,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2° EDUC. PRIMARIA,NaN
945,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FI,NaN

In [498]:
df['Especialidad'].unique().tolist()

['MEDICINA HUMANA',
 'ENFERMERIA',
 'DERECHO Y CIENCIA POLITICAS',
 'FILOSOFIA, PSICOLOGIA Y CIEN',
 '1° DERECHO Y CIENCIA',
 'POLITICAS',
 '2° COMUNICACION SOCIAL',
 '2° LENGUA Y LITERATURA',
 'MATEMATICA, COMPUTACION Y',
 'FI',
 '2° FILOSOFIA, PSICOLOGIA Y',
 'CIENCIAS SOCIALES',
 '2° EDUC. PRIMARIA',
 'COMUNICACION SOCIAL',
 'IDIOMAS: INGLES - FRANCES',
 '2° HISTORIA, GEOGRAFIA Y',
 'EDUC. INICIAL',
 'EDUC. PRIMARIA',
 'HISTORIA, GEOGRAFIA Y CIENCI',
 'LENGUA Y LITERATURA',
 '1° EDUC. INICIAL']

In [546]:
def test(row):
    text_especialidad = row['Especialidad']
    next_position = row.name+1
    salir = 0
    while(salir!=-1):  
        if next_position<=(len(df)-1):
            next_row = df.iloc[next_position]
            if pd.isna(next_row['#']):
                text_especialidad+=(" "+next_row['Especialidad'].strip())
                next_position+=1
                
            else:
                salir = -1
        else:
            salir = -1
    row['Especialidad'] = text_especialidad
    return row
    
f1 = df.apply(test,axis='columns')

In [500]:
f1['Especialidad'].unique().tolist()

['MEDICINA HUMANA',
 'ENFERMERIA',
 'DERECHO Y CIENCIA POLITICAS',
 'FILOSOFIA, PSICOLOGIA Y CIEN',
 '1° DERECHO Y CIENCIA POLITICAS 2° COMUNICACION SOCIAL',
 'POLITICAS 2° COMUNICACION SOCIAL',
 '2° COMUNICACION SOCIAL',
 '1° DERECHO Y CIENCIA POLITICAS 2° LENGUA Y LITERATURA',
 'POLITICAS 2° LENGUA Y LITERATURA',
 '2° LENGUA Y LITERATURA',
 'MATEMATICA, COMPUTACION Y FI',
 'FI',
 '1° DERECHO Y CIENCIA POLITICAS 2° FILOSOFIA, PSICOLOGIA Y CIENCIAS SOCIALES',
 'POLITICAS 2° FILOSOFIA, PSICOLOGIA Y CIENCIAS SOCIALES',
 '2° FILOSOFIA, PSICOLOGIA Y CIENCIAS SOCIALES',
 'CIENCIAS SOCIALES',
 '1° DERECHO Y CIENCIA POLITICAS 2° EDUC. PRIMARIA',
 'POLITICAS 2° EDUC. PRIMARIA',
 '2° EDUC. PRIMARIA',
 'COMUNICACION SOCIAL',
 'IDIOMAS: INGLES - FRANCES',
 '1° DERECHO Y CIENCIA POLITICAS 2° HISTORIA, GEOGRAFIA Y CIENCIAS SOCIALES',
 'POLITICAS 2° HISTORIA, GEOGRAFIA Y CIENCIAS SOCIALES',
 '2° HISTORIA, GEOGRAFIA Y CIENCIAS SOCIALES',
 'EDUC. INICIAL',
 'EDUC. PRIMARIA',
 'HISTORIA, GEOGRAFIA Y CIENCI',
 'LENGUA Y LITERATURA',
 '1° EDUC. INICIAL 2° EDUC. PRIMARIA']

In [547]:
notNanIngreso = f1['Ingreso'].notna()
f2 = f1.loc[notNanIngreso]

In [502]:
f2['Especialidad'].unique().tolist()

['MEDICINA HUMANA',
 'ENFERMERIA',
 'DERECHO Y CIENCIA POLITICAS',
 'FILOSOFIA, PSICOLOGIA Y CIEN',
 '1° DERECHO Y CIENCIA POLITICAS 2° COMUNICACION SOCIAL',
 '1° DERECHO Y CIENCIA POLITICAS 2° LENGUA Y LITERATURA',
 'MATEMATICA, COMPUTACION Y FI',
 '1° DERECHO Y CIENCIA POLITICAS 2° FILOSOFIA, PSICOLOGIA Y CIENCIAS SOCIALES',
 '1° DERECHO Y CIENCIA POLITICAS 2° EDUC. PRIMARIA',
 'COMUNICACION SOCIAL',
 'IDIOMAS: INGLES - FRANCES',
 '1° DERECHO Y CIENCIA POLITICAS 2° HISTORIA, GEOGRAFIA Y CIENCIAS SOCIALES',
 'EDUC. INICIAL',
 'EDUC. PRIMARIA',
 'HISTORIA, GEOGRAFIA Y CIENCI',
 'LENGUA Y LITERATURA',
 '1° EDUC. INICIAL 2° EDUC. PRIMARIA']

In [503]:
f2.shape

(943, 12)

In [506]:
f2

,#,Carné,Apellidos y Nombres,Bu,Ma,Puntaje,Bu.1,Ma.1,Puntaje.1,Examen,Especialidad,Ingreso
0,1.0,24230041.0,MONZÓN RODRÍGUEZ PAOLO FABIANO,25.0,8.0,93.598,30.0,18.0,133.992,227.590,MEDICINA HUMANA,SI
1,2.0,24230493.0,AMOROZ SANCHEZ MIGUEL ANGEL,26.0,8.0,97.668,30.0,25.0,126.845,224.513,MEDICINA HUMANA,SI
2,3.0,24230193.0,CUYATE CALDERON DIEGO STALIN,27.0,6.0,103.776,27.0,21.0,115.692,219.468,MEDICINA HUMANA,SI
3,4.0,24230353.0,ZAVALETA AGUIRRE BRYAN JHOSUE,21.0,3.0,82.413,28.0,8.0,134.044,216.457,MEDICINA HUMANA,SI
4,5.0,24230158.0,CRUZ ESPEJO ANDERSON ALEXANDER,22.0,7.0,82.407,30.0,18.0,133.992,216.399,MEDICINA HUMANA,SI
...,...,...,...,...,...,...,...,...,...,...,...,...
1019,939.0,24230381.0,ROSSELL GILIO FIORELLA STEFANY,8.0,29.0,3.009,7.0,43.0,-8.350,-5.341,MEDICINA HUMANA,NO
1020,940.0,31230071.0,ZAPATA PEREZ YOMARA SOLEDAD,2.0,19.0,-11.221,4.0,18.0,1.938,-9.283,EDUC. INICIAL,NO
1021,941.0,24230133.0,PELAEZ CORDOVA AKEMI MARIA,7.0,19.0,9.129,4.0,39.0,-19.503,-10.374,MEDICINA HUMANA,NO
1022,942.0,32230014.0,QUINTANA SILVA SHEYLA VANESSA,6.0,34.0,-10.226,9.0,51.0,-6.360,-16.586,EDUC. PRIMARIA,NO
1023,943.0,21230109.0,CASHPA LEON ELEAZAR LIZANDRO,8.0,32.0,-0.048,6.0,52.0,-22.618,-22.666,ENFERMERIA,NO

In [548]:
def add_new_column(row):
    text_new_column = 'DESCARTADO'
    if row['Especialidad'].startswith('1'):
        text_separate = row['Especialidad'].split('2°')
        text_new_column = text_separate[1].strip()
        row['Especialidad'] = text_separate[0][2:].strip()
        
    row['Segunda Opcion'] = text_new_column
    return row
f3 = f2.apply(add_new_column,axis='columns')
f3[f3['Ingreso']=='Seg Opc']

,#,Carné,Apellidos y Nombres,Bu,Ma,Puntaje,Bu.1,Ma.1,Puntaje.1,Examen,Especialidad,Ingreso,Segunda Opcion
110,111.0,39230092.0,LOPEZ TORRES DAVID ALI,9.0,5.0,31.535,20.0,10.0,91.370,122.905,DERECHO Y CIENCIA POLITICAS,Seg Opc,COMUNICACION SOCIAL
113,112.0,39230120.0,CHUCHON ROJAS OMAR RONNIE,10.0,6.0,34.586,20.0,13.0,88.307,122.893,DERECHO Y CIENCIA POLITICAS,Seg Opc,LENGUA Y LITERATURA
116,113.0,39230025.0,ROBLES PORTOCARRERO RUTH ABIGAIL,9.0,6.0,30.516,21.0,14.0,92.365,122.881,DERECHO Y CIENCIA POLITICAS,Seg Opc,COMUNICACION SOCIAL
123,118.0,39230082.0,BRUNO ACOSTA MAURICIO EFRAIN,10.0,3.0,37.643,19.0,12.0,84.249,121.892,DERECHO Y CIENCIA POLITICAS,Seg Opc,COMUNICACION SOCIAL
129,122.0,39230040.0,REYES LLAMA ANELKA NELIDA,11.0,6.0,38.656,18.0,9.0,82.233,120.889,DERECHO Y CIENCIA POLITICAS,Seg Opc,LENGUA Y LITERATURA
146,136.0,39230083.0,ABURTO MORA ROGER MAXKENLEE,12.0,19.0,29.479,22.0,26.0,85.192,114.671,DERECHO Y CIENCIA POLITICAS,Seg Opc,"FILOSOFIA, PSICOLOGIA Y CIENCIAS SOCIALES"
151,138.0,39230044.0,RAMIREZ MENDOZA GIULLIANA MELVA,9.0,4.0,32.554,17.0,5.0,81.238,113.792,DERECHO Y CIENCIA POLITICAS,Seg Opc,COMUNICACION SOCIAL
154,139.0,39230097.0,GIL ASMAD ANTONELLA ROSVIT,10.0,5.0,35.605,17.0,8.0,78.175,113.780,DERECHO Y CIENCIA POLITICAS,Seg Opc,EDUC. PRIMARIA
157,140.0,39230109.0,SALAZAR PALMA HILARY ESTER MERCEDES,16.0,24.0,40.664,22.0,38.0,72.940,113.604,DERECHO Y CIENCIA POLITICAS,Seg Opc,"FILOSOFIA, PSICOLOGIA Y CIENCIAS SOCIALES"
172,152.0,39230102.0,LEON PALACIOS ALEJANDRO GERARD,12.0,9.0,39.669,16.0,12.0,69.012,108.681,DERECHO Y CIENCIA POLITICAS,Seg Opc,"HISTORIA, GEOGRAFIA Y CIENCIAS SOCIALES"
181,158.0,39230068.0,PASCUAL BLAS NICOLLE NASHALLY ISAMAR,11.0,7.0,37.637,15.0,7.0,69.038,106.675,DERECHO Y CIENCIA POLITICAS,Seg Opc,COMUNICACION SOCIAL
192,167.0,39230034.0,BARRANTES INFANTES KAROL PIERINA,5.0,10.0,10.160,21.0,13.0,93.386,103.546,DERECHO Y CIENCIA POLITICAS,Seg Opc,"HISTORIA, GEOGRAFIA Y CIENCIAS SOCIALES"
198,170.0,39230142.0,TORRES SABINO ANDREA JULIANA,8.0,10.0,22.370,18.0,11.0,80.191,102.561,DERECHO Y CIENCIA POLITICAS,Seg Opc,COMUNICACION SOCIAL
222,192.0,39230056.0,VALVERDE ALCANTARA SARA NAYELY,11.0,4.0,40.694,16.0,24.0,56.760,97.454,DERECHO Y CIENCIA POLITICAS,Seg Opc,LENGUA Y LITERATURA
243,211.0,39230086.0,MEJIA LLONTOP JULIA CRISTINA,8.0,5.0,27.465,16.0,15.0,65.949,93.414,DERECHO Y CIENCIA POLITICAS,Seg Opc,"FILOSOFIA, PSICOLOGIA Y CIENCIAS SOCIALES"
252,217.0,39230021.0,BOZZETA MINCHOLA SIBYL DEJIREH,12.0,7.0,41.707,13.0,15.0,50.712,92.419,DERECHO Y CIENCIA POLITICAS,Seg Opc,LENGUA Y LITERATURA
260,223.0,39230062.0,MATOS VERANO TABITA DAMARIZ,11.0,11.0,33.561,15.0,18.0,57.807,91.368,DERECHO Y CIENCIA POLITICAS,Seg Opc,EDUC. PRIMARIA
366,327.0,39230041.0,NUÑEZ CHIMPA NAYAP SANTOS,9.0,7.0,29.497,12.0,15.0,45.633,75.130,DERECHO Y CIENCIA POLITICAS,Seg Opc,"FILOSOFIA, PSICOLOGIA Y CIENCIAS SOCIALES"
405,363.0,39230080.0,RAMOS GARCIA ANDERSON YIMI,12.0,13.0,35.593,12.0,26.0,34.402,69.995,DERECHO Y CIENCIA POLITICAS,Seg Opc,"FILOSOFIA, PSICOLOGIA Y CIENCIAS SOCIALES"
431,386.0,39230148.0,GONZALES CHAUCA SANAVEL STHEFANNY,6.0,16.0,8.116,17.0,26.0,59.797,67.913,DERECHO Y CIENCIA POLITICAS,Seg Opc,"FILOSOFIA, PSICOLOGIA Y CIENCIAS SOCIALES"
441,393.0,39230146.0,DE LA CRUZ ASTO ERICK FERNANDO,9.0,16.0,20.326,15.0,29.0,46.576,66.902,DERECHO Y CIENCIA POLITICAS,Seg Opc,"HISTORIA, GEOGRAFIA Y CIENCIAS SOCIALES"
453,402.0,39230107.0,GONZALES LOLI ELIANA LOURDES,9.0,12.0,24.402,14.0,29.0,41.497,65.899,DERECHO Y CIENCIA POLITICAS,Seg Opc,LENGUA Y LITERATURA
457,404.0,39230012.0,MEZA CASTILLO ARLETTE DARIMI,8.0,3.0,29.503,8.0,5.0,35.527,65.030,DERECHO Y CIENCIA POLITICAS,Seg Opc,EDUC. PRIMARIA
479,424.0,39230113.0,TAMARA MORALES CRISTIAN ALEXIS,13.0,8.0,44.758,7.0,18.0,17.175,61.933,DERECHO Y CIENCIA POLITICAS,Seg Opc,"FILOSOFIA, PSICOLOGIA Y CIENCIAS SOCIALES"
489,431.0,39230026.0,SOTO RAMOS JHON CESAR,14.0,23.0,33.543,13.0,37.0,28.250,61.793,DERECHO Y CIENCIA POLITICAS,Seg Opc,"FILOSOFIA, PSICOLOGIA Y CIENCIAS SOCIALES"
507,446.0,39230053.0,CASTRO OCAÑA DIEGO ADRIAN,13.0,14.0,38.644,9.0,24.0,21.207,59.851,DERECHO Y CIENCIA POLITICAS,Seg Opc,"HISTORIA, GEOGRAFIA Y CIENCIAS SOCIALES"
550,486.0,39230117.0,ROJAS SALINAS DIEGO FERNANDO,5.0,9.0,11.179,12.0,15.0,45.633,56.812,DERECHO Y CIENCIA POLITICAS,Seg Opc,"FILOSOFIA, PSICOLOGIA Y CIENCIAS SOCIALES"
559,492.0,39230096.0,PAREDES GUTIERREZ ESTRELLITA MARYALEJANDRA,7.0,8.0,20.338,11.0,20.0,35.449,55.787,DERECHO Y CIENCIA POLITICAS,Seg Opc,EDUC. PRIMARIA
593,523.0,39230140.0,AVILA CUEVA JAMILLE MASHIELL,7.0,5.0,23.395,8.0,12.0,28.380,51.775,DERECHO Y CIENCIA POLITICAS,Seg Opc,EDUC. PRIMARIA
675,602.0,39230134.0,LOPEZ VIERA IVAN PAOLO,0.0,4.0,-4.076,14.0,22.0,48.644,44.568,DERECHO Y CIENCIA POLITICAS,Seg Opc,"HISTORIA, GEOGRAFIA Y CIENCIAS SOCIALES"
693,617.0,31230070.0,COLLAZOS HUAYNACAQUI NAYELY PAOLI,6.0,11.0,13.211,9.0,16.0,29.375,42.586,EDUC. INICIAL,Seg Opc,EDUC. PRIMARIA
697,620.0,39230069.0,RODRIGUEZ HERNANDEZ JACKELINE ELIZABETH,13.0,24.0,28.454,12.0,46.0,13.982,42.436,DERECHO Y CIENCIA POLITICAS,Seg Opc,EDUC. PRIMARIA

In [549]:
f4 = f3.set_index('#')
f4

,Carné,Apellidos y Nombres,Bu,Ma,Puntaje,Bu.1,Ma.1,Puntaje.1,Examen,Especialidad,Ingreso,Segunda Opcion
#,,,,,,,,,,,,
1.0,24230041.0,MONZÓN RODRÍGUEZ PAOLO FABIANO,25.0,8.0,93.598,30.0,18.0,133.992,227.590,MEDICINA HUMANA,SI,DESCARTADO
2.0,24230493.0,AMOROZ SANCHEZ MIGUEL ANGEL,26.0,8.0,97.668,30.0,25.0,126.845,224.513,MEDICINA HUMANA,SI,DESCARTADO
3.0,24230193.0,CUYATE CALDERON DIEGO STALIN,27.0,6.0,103.776,27.0,21.0,115.692,219.468,MEDICINA HUMANA,SI,DESCARTADO
4.0,24230353.0,ZAVALETA AGUIRRE BRYAN JHOSUE,21.0,3.0,82.413,28.0,8.0,134.044,216.457,MEDICINA HUMANA,SI,DESCARTADO
5.0,24230158.0,CRUZ ESPEJO ANDERSON ALEXANDER,22.0,7.0,82.407,30.0,18.0,133.992,216.399,MEDICINA HUMANA,SI,DESCARTADO
...,...,...,...,...,...,...,...,...,...,...,...,...
939.0,24230381.0,ROSSELL GILIO FIORELLA STEFANY,8.0,29.0,3.009,7.0,43.0,-8.350,-5.341,MEDICINA HUMANA,NO,DESCARTADO
940.0,31230071.0,ZAPATA PEREZ YOMARA SOLEDAD,2.0,19.0,-11.221,4.0,18.0,1.938,-9.283,EDUC. INICIAL,NO,DESCARTADO
941.0,24230133.0,PELAEZ CORDOVA AKEMI MARIA,7.0,19.0,9.129,4.0,39.0,-19.503,-10.374,MEDICINA HUMANA,NO,DESCARTADO
942.0,32230014.0,QUINTANA SILVA SHEYLA VANESSA,6.0,34.0,-10.226,9.0,51.0,-6.360,-16.586,EDUC. PRIMARIA,NO,DESCARTADO
943.0,21230109.0,CASHPA LEON ELEAZAR LIZANDRO,8.0,32.0,-0.048,6.0,52.0,-22.618,-22.666,ENFERMERIA,NO,DESCARTADO

In [559]:
f5 = f4
f5.index = f5.index.astype(int)
f5

,Carné,Apellidos y Nombres,Bu,Ma,Puntaje,Bu.1,Ma.1,Puntaje.1,Examen,Especialidad,Ingreso,Segunda Opcion
#,,,,,,,,,,,,
1,24230041.0,MONZÓN RODRÍGUEZ PAOLO FABIANO,25.0,8.0,93.598,30.0,18.0,133.992,227.590,MEDICINA HUMANA,SI,DESCARTADO
2,24230493.0,AMOROZ SANCHEZ MIGUEL ANGEL,26.0,8.0,97.668,30.0,25.0,126.845,224.513,MEDICINA HUMANA,SI,DESCARTADO
3,24230193.0,CUYATE CALDERON DIEGO STALIN,27.0,6.0,103.776,27.0,21.0,115.692,219.468,MEDICINA HUMANA,SI,DESCARTADO
4,24230353.0,ZAVALETA AGUIRRE BRYAN JHOSUE,21.0,3.0,82.413,28.0,8.0,134.044,216.457,MEDICINA HUMANA,SI,DESCARTADO
5,24230158.0,CRUZ ESPEJO ANDERSON ALEXANDER,22.0,7.0,82.407,30.0,18.0,133.992,216.399,MEDICINA HUMANA,SI,DESCARTADO
...,...,...,...,...,...,...,...,...,...,...,...,...
939,24230381.0,ROSSELL GILIO FIORELLA STEFANY,8.0,29.0,3.009,7.0,43.0,-8.350,-5.341,MEDICINA HUMANA,NO,DESCARTADO
940,31230071.0,ZAPATA PEREZ YOMARA SOLEDAD,2.0,19.0,-11.221,4.0,18.0,1.938,-9.283,EDUC. INICIAL,NO,DESCARTADO
941,24230133.0,PELAEZ CORDOVA AKEMI MARIA,7.0,19.0,9.129,4.0,39.0,-19.503,-10.374,MEDICINA HUMANA,NO,DESCARTADO
942,32230014.0,QUINTANA SILVA SHEYLA VANESSA,6.0,34.0,-10.226,9.0,51.0,-6.360,-16.586,EDUC. PRIMARIA,NO,DESCARTADO
943,21230109.0,CASHPA LEON ELEAZAR LIZANDRO,8.0,32.0,-0.048,6.0,52.0,-22.618,-22.666,ENFERMERIA,NO,DESCARTADO

In [567]:
f5.columns = ['CARNE',
              'APELLIDOS Y NOMBRES',
              'APTITUD ACADEMICA - BUENAS',
              'APTITUD ACADEMICA - MALAS',
              'APTITUD ACADEMICA PUNTAJE',
              'CONOCIMIENTOS - BUENAS',
              'CONOCIMIENTOS - MALAS',
              'CONOCIMIENTOS PUNTAJE',
              'PUNTAJE FINAL',
             'ESPECIALIDAD',
             'INGRESO',
             'SEGUNDA OPCION']
f5.head()

,CARNE,APELLIDOS Y NOMBRES,APTITUD ACADEMICA - BUENAS,APTITUD ACADEMICA - MALAS,APTITUD ACADEMICA PUNTAJE,CONOCIMIENTOS - BUENAS,CONOCIMIENTOS - MALAS,CONOCIMIENTOS PUNTAJE,PUNTAJE FINAL,ESPECIALIDAD,INGRESO,SEGUNDA OPCION
#,,,,,,,,,,,,
1,24230041.0,MONZÓN RODRÍGUEZ PAOLO FABIANO,25.0,8.0,93.598,30.0,18.0,133.992,227.590,MEDICINA HUMANA,SI,DESCARTADO
2,24230493.0,AMOROZ SANCHEZ MIGUEL ANGEL,26.0,8.0,97.668,30.0,25.0,126.845,224.513,MEDICINA HUMANA,SI,DESCARTADO
3,24230193.0,CUYATE CALDERON DIEGO STALIN,27.0,6.0,103.776,27.0,21.0,115.692,219.468,MEDICINA HUMANA,SI,DESCARTADO
4,24230353.0,ZAVALETA AGUIRRE BRYAN JHOSUE,21.0,3.0,82.413,28.0,8.0,134.044,216.457,MEDICINA HUMANA,SI,DESCARTADO
5,24230158.0,CRUZ ESPEJO ANDERSON ALEXANDER,22.0,7.0,82.407,30.0,18.0,133.992,216.399,MEDICINA HUMANA,SI,DESCARTADO

In [571]:
f5.to_csv('data_transformada.csv',index=False)

In [588]:
f5.describe().round()

,CARNE,APTITUD ACADEMICA - BUENAS,APTITUD ACADEMICA - MALAS,APTITUD ACADEMICA PUNTAJE,CONOCIMIENTOS - BUENAS,CONOCIMIENTOS - MALAS,CONOCIMIENTOS PUNTAJE,PUNTAJE FINAL
count,943.0,943.0,943.0,943.0,943.0,943.0,943.0,943.0
mean,27494208.0,9.0,11.0,28.0,11.0,19.0,37.0,65.0
std,6328295.0,5.0,7.0,22.0,6.0,11.0,31.0,47.0
min,21230001.0,0.0,0.0,-17.0,0.0,0.0,-23.0,-23.0
25%,24230074.0,6.0,6.0,12.0,7.0,12.0,15.0,32.0
50%,24230320.0,9.0,9.0,24.0,11.0,18.0,32.0,58.0
75%,32230006.0,12.0,14.0,42.0,14.0,25.0,51.0,88.0
max,39230148.0,27.0,35.0,104.0,32.0,52.0,144.0,228.0